### ISSUE TITLE
Does this work with Windows?

### ISSUE THREAD

**Issue by spielmirdasliedvomkoks** [C3RV1/UndertaleNDS#25]
See title. Sorry if that question sounds stupid. I'm not very experienced when it comes to coding. I tried creating the ROM by altering the commands for Windows and splitting the individual lines from the .sh but I got stuck... The last input and output are:

I:\undertale_nds>python patch_files.py tools.zip.patch tools
Traceback (most recent call last):
  File "I:\undertale_nds\patch_files.py", line 40, in <module>
    main(sys.argv[1], "data.win", sys.argv[2] + ".zip")
  File "I:\undertale_nds\patch_files.py", line 30, in main
    cipher = AES.new(key, AES.MODE_EAX, nonce)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\Crypto\Cipher\AES.py", line 228, in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\Crypto\Cipher\__init__.py", line 79, in _create_cipher
    return modes[mode](factory, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\Crypto\Cipher\_mode_eax.py", line 408, in _create_eax_cipher
    return EaxMode(factory, key, nonce, mac_len, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\Crypto\Cipher\_mode_eax.py", line 103, in __init__
    raise ValueError("Nonce cannot be empty in EAX mode")
ValueError: Nonce cannot be empty in EAX mode

If anyone could point me in the right direction I'd be very grateful!

**Comment by C3RV1** [comment]
try changing line 40 in patch_files.py to:
main(sys.argv[2], "data.win", sys.argv[3] + ".zip")

**Comment by C3RV1** [comment]
huh, how strange... still, if you want I could send you by some means the built nds file. for now the game uses the same assets found in the demo, which are public

**Comment by spielmirdasliedvomkoks** [comment]
> huh, how strange... still, if you want I could send you by some means the built nds file. for now the game uses the same assets found in the demo, which are public

Avesome, sent you an email

**Comment by C3RV1** [comment]
I'm right now on my phone. Once I get back I'll send it over!
