### ISSUE TITLE
nitrofs.zip is not a zip file error

### ISSUE THREAD

**Issue by OofChair** [C3RV1/UndertaleNDS#26]
Hi,
I keep getting this error trying to run `python3 tools/patch_files.py ../nitrofs.zip.patch ../nitrofs`:

```Game version not supported (hash does not match)
Traceback (most recent call last):
  File "C:\Users\admin\Downloads\UndertaleNDS\tools\patch_files.py", line 41, in <module>
    shutil.unpack_archive(sys.argv[2] + ".zip", sys.argv[2], 'zip')
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\shutil.py", line 1318, in unpack_archive
    func(filename, extract_dir, **dict(format_info[2]), **filter_kwargs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\shutil.py", line 1214, in _unpack_zipfile
    raise ReadError("%s is not a zip file" % filename)
shutil.ReadError: ../nitrofs.zip is not a zip file
```

**Comment by C3RV1** [comment]
Can you find any generated nitrofs.zip or tools.zip files in the folders?

**Comment by OofChair** [comment]
yeah, when i open them there's no files in the .zip

**Comment by C3RV1** [comment]
what's the size of the files? and could you also check the size of the .patch files?

**Comment by OofChair** [comment]
the zips are 0kb 
tools patch: 434kb
nitrofs patch: 38,546kb

**Comment by C3RV1** [comment]
mhm somehow the zip files weren't created correctly, let me check the code

**Comment by C3RV1** [comment]
isn't there a Undertale.nds file?

**Comment by OofChair** [comment]
yep there is an undertale.nds file, that works fine but it has the game vers not supported message

**Comment by C3RV1** [comment]
if you get the version not supported error that's probably why the zip files weren't generated correctly. without the right game.win the files won't be created

**Comment by Aly3663** [comment]
Where do i get the files?

**Comment by SgtSalmon** [comment]
It’s under your steam game files ( browse local files on steam)
