### ISSUE TITLE
Patch Error on Fedora 39

### ISSUE THREAD

**Issue by paulth67** [C3RV1/UndertaleNDS#39]
Hello, so i tried to patch my data.win and there is an error with the patch :

```
Traceback (most recent call last):
  File "/home/.../UndertaleNDS/patcher.py", line 84, in <module>
    main()
  File "/home/.../UndertaleNDS/patcher.py", line 71, in main
    patch(patch_file, key, zip_path)
  File "/home/.../UndertaleNDS/patcher.py", line 38, in patch
    cipher = AES.new(key, AES.MODE_EAX, nonce)
                          ^^^^^^^^^^^^
AttributeError: module 'Crypto.Cipher.AES' has no attribute 'MODE_EAX'. Did you mean: 'MODE_ECB'?
```

I don't know if it's a problem with Devkit...

**Comment by x1cOfficial** [comment]
are you using pycrypto or pycryptodome? the patcher.py script says it needs pycryprodome and pycrypto isn't being updated anymore
